#!/bin/bash
set -e
script_dir=$(dirname $0)

mkdir -p $script_dir/../resources

vault read -field=value techascent/google-sheets-key > $script_dir/../resources/creds.json

id=$(vault read -field=value techascent/google-sheets-id)
echo "{:id \"$id\"}" > $script_dir/../resources/user-config.edn
